name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install
        run: |
          npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Publish to registry
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git status
          npm run release:ci
